### ISSUE TITLE
Memory Warning

### ISSUE THREAD

**Issue by obliviux** [mmackh/MAImagePickerController-of-InstaPDF#1]
First of all, thank you for this wonderful library! I am trying to implement it, but everytime the captureSession start running, or the image is cropped, I get a memory warning (on both iPhone 4s and 5) and often some crashes. The normal RAM usage is around 2-3 MB, when the MAImagePickerController is called the memory jumps to 32MB and then to over 90 when the image is cropped.

**Comment by geowarsong** [comment]
try to save in direcotry and then load it from path. or use 

> CGBitmapInfo bmInfo = kCGImageAlphaPremultipliedLast | kCGBitmapByteOrder32Big;
