### ISSUE TITLE
This project is not compiling for Xcode 6 and iOS 8

### ISSUE THREAD

**Issue by sambudda** [mmackh/MAImagePickerController-of-InstaPDF#9]
I get the following compile error when I do Xcode recommended upgrade

No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=arm64, VALID_ARCHS=armv7 armv7s).
![screen shot 2015-07-17 at 10 38 12 am](https://cloud.githubusercontent.com/assets/3536867/8749508/09813dd2-2c70-11e5-9055-9113728ad06c.png)

**Comment by sambudda** [comment]
http://stackoverflow.com/questions/22328882/xcode-5-1-no-architectures-to-compile-for-only-active-arch-yes-active-arch-x

**Comment by brave1024** [comment]
I have the same problem, everybody helps?
